### ISSUE TITLE
attach_disk fails when run before /etc/rc2.d/S15install.sh completes

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi-release#145] opened 2016-07-17 15:50 UTC
While attempting to deploy cloud foundry, jobs with persistent disks often fail with a disk attach error like this:

```
E, [2016-07-17 14:24:00 #3630] [task:979] ERROR -- DirectorJobRunner: Attaching disk '12165173' to VM '22469545': Failed to attach volume `12165173` to virtual guest `22469545`: Failed to attach disk '12165173' to virtual guest '22469545'
```

This has happened several times. The only consistent symptom I find is that the `/etc/rc2.d/S15install.sh` is running on the failed VMs but is not running on the successful VMs. This may be some sort of race between the softlayer initialization scripts and the execution of the agent.

Since `/etc/rc2.d/S15install.sh` is looping in the following block:

``` sh
# wget will default retry 20 times
wget -O "/root/nettest" "http://${DOWNLOAD_HOST}/install_scripts/nettest"
while true
  do
    if [ -s "/root/nettest" ]
    then
      rm -f "/root/nettest"
      break
    else
      sleep 6
      wget -O "/root/nettest" "http://${DOWNLOAD_HOST}/install_scripts/nettest"
    fi
done
```

the multipath tools setup script (`/etc/rc2.d/S20multipath-tools`) never runs. When the multipath tools setup script doesn't run, the polling of `dmsetup ls` that's done by the CPI consistently returns with no disks.

The root cause appears to be that `$DOWNLOAD_HOST` is not set. An strace of the running script shows that:

```
[pid 31051] execve("/usr/bin/wget", ["wget", "-O", "/root/nettest", "http:///install_scripts/nettest"], [/* 12 vars */]) = 0
```

I'm guessing that the value is supposed to come from  `/root/provisioningConfiguration.cfg` but that file has been deleted. That implies that the system was rebooted during the 30 second sleep window of the `S15install.sh` script since the actions before the sleep completed but the actions after the sleep did not.

``` sh
    update_status INSTALL_COMPLETE
    # rm -f "/root/swinstall.ini"
    rm -f "/root/provisioningConfiguration.cfg"
    rm -f "/root/base_functions.sh"
    rm -f "${TXN_INSTALL_LOG}"
    sleep 30
    rm /etc/rc2.d/S15install.sh
    rm /root/install.sh
    #/sbin/shutdown -r now

rm /etc/rc2.d/S15install.sh
rm /root/install.sh
rm /etc/systemd/system/installsh.service
```

**Comment by mattcui** [comment] 2016-08-01 06:36
@sykesm We saw such problem frequently when deploying a Whisk environment in dal09. It's because there needs much longer time (more than 5 mins) between placing a disk order and the disk is ready for attaching, in general, it only needs to take 1 min, but something wrong with SL these days, it needs much longer time, the [default timeout duration](https://github.com/maximilien/softlayer-go/blob/master/services/softlayer_network_storage.go#L19) is 5 mins. So we opened [feature 127370877](https://www.pivotaltracker.com/story/show/127370877) to extend the timeout value to 10 mins and allow the user to set the timeout value in the bad performance situation.

**Comment by sykesm** [comment] 2016-08-01 10:39
You are conflating problems. This issue has to do with the fact that something is causing a reboot before the init scripts complete. This is not a timeout that can be extended.

If you read what I wrote in the issue, you will see there is no way to recover from this problem other than to recreate the image or manually run the remaining init scripts.

**Comment by jianqiu** [comment] 2016-08-04 09:19
@sykesm,
Thanks for your detailed description about the issue.
Do you have the steps to consistently reproduce this problem?
Where to find the init script `/etc/rc2.d/S15install.sh` and `/root/provisioningConfiguration.cfg` before I could not find them on a successfully provisioned vm of Softlayer. Thanks!

**Comment by sykesm** [comment] 2016-08-04 14:04
@jianqiu I don't have a way of consistently doing it. Your best bet is to do a fresh deployment with a bunch of VMs that have persistent disks; that will likely cause you to hit the problem.

**Comment by mattcui** [comment] 2016-08-04 15:27
@jianqiu the symptom of the problem is pretty much like today's issue we just resolved, but we didn't get a chance to check what @sykesm described in this issue. The cause of the problem seemed to be that the persistent disk is not authorized to the VM properly, from the SL portal, we saw it's authorized, but it failed to run discovery or session login with iscsiadmin tool. We have to re-authorized the disk from SL portal, then everything is fine. I am not sure if today's problem is similar to this one, @jianqiu in eCPI code, there didn't re-authorize the disk if it's already authorized, right? If so, I think we may need to improve the code to get the disk re-authorized, what do you think? Thanks.

**Comment by sykesm** [comment] 2016-08-04 17:41
This problem (#145) is *not* about authorization. This problem is explicitly:

> the multipath tools setup script (/etc/rc2.d/S20multipath-tools) never runs

This is a problem that occurs during system initialization that prevents `dmsetup ls` from functioning correctly.

**Comment by maximilien** [comment] 2016-11-23 00:52
Hi, @gu-bin can you update me on this? You worked on multipath last, correct?

/cc @mattcui @jianqiu

**Comment by mattcui** [comment] 2017-04-11 03:36
Closing this since cannot repro. Please re-open if you see it again in new release and can provide steps to repro.

/cc @maximilien

**Closed by mattcui** 2017-04-11 03:36 UTC
Labels: scheduled
